language: csharp
solution: DealFinder.sln
language: csharp
mono: none
dotnet: 2.1.4
script:
 - dotnet restore
 - cd DealFinder.Api.Tests && dotnet test
 - cd ../DealFinder.Core.Tests && dotnet test
 - cd ../DealFinder.Data.Tests && dotnet test

notifications:
  email: false