language: csharp
solution: DealFinder.sln
language: csharp
mono: none
dotnet: 2.1.4

before_script:
  - npm install -g @angular/cli

script:
 - dotnet restore
 - cd DealFinder.Api.Tests && dotnet test
 - cd ../DealFinder.Core.Tests && dotnet test
 - cd ../DealFinder.Data.Tests && dotnet test
 - cd ../DealFinder.Web && yarn && ng build --prod

notifications:
  email: false
  webhooks:
  urls:
    - https://fyp.miloszdura.com/api/deploy
  on_start: false
  on_success: always
  on_failure: false
